Fix bug wrong password throw exception
chaintex/TomoSwap pull request #16
Opened 2019-03-15 08:30 UTC by marknguyen85

Fix bug wrong password throw exception

2019-03-15 09:13 UTC, artwooood requested changes

2019-03-15 09:13 UTC, trungnx-kyber commented on src/sagas/swapSaga.js
> +    yield put(txActions.setConfirmingError(error.message));
This should be leaved as it is for now. We still have other services for importing account that return the error as string, not object.

2019-03-15 09:13 UTC, trungnx-kyber commented on src/services/accountServices/KeystoreService.js
> +      throw error;
Can you throw `error` here as string: `throw error.message`

2019-03-15 09:13 UTC, trungnx-kyber commented on src/services/accountServices/KeystoreService.js
> +    let account = null;
I think the whole process of unlocking account worths to be separated into another function. And here, we just need to call `account = this.unlockAccount()`

2019-03-15 09:19 UTC, marknguyen85 commented on src/services/accountServices/KeystoreService.js
> +      throw error;
ok

2019-03-16 03:12 UTC, marknguyen85 commented on src/services/accountServices/KeystoreService.js
> +    let account = null;
yes i will implement on next times.

2019-03-16 03:34 UTC, manhlx3006 approved these changes
Look good to me

2019-03-16 03:36 UTC, artwooood approved these changes

2019-03-16 03:38 UTC, merged